[WIP] Add edit and delete
ezerssss/unihub pull request #103
Opened 2023-07-10 14:38 UTC by HansGabriel

2023-07-11 03:51 UTC, ezerssss requested changes

2023-07-11 03:51 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +          onPress={goToEditSell(product)}
`() => goToEditSell(product)`

2023-07-11 03:51 UTC, ezerssss commented on screens/SpecificProduct/SpecificProduct.tsx
> +      onPress={goToEditSell(product)}
`() => goToEditSell(product)`

2023-07-11 03:51 UTC, ezerssss commented on helpers/upload.ts
> +  return specificPart;
is this more robust than my original implementation? if so, how so?

2023-07-11 03:51 UTC, ezerssss commented on screens/Sell/EditSell.tsx
this seems to be the exact same screen as `Sell.tsx` with just additional buttons for `Update` and some additional functions, can you instead:

have an optional screen parameter sa `Sell.tsx`, and you can then set the states with the parameter but you just need to check if the parameter exist, something like:

`const [title, setTitle] = useState(product.title ?? "");`

you can then just conditionally render the update button if the parameter exist

2023-07-11 04:08 UTC, HansGabriel commented on helpers/upload.ts
> +  return specificPart;
the original implementation wasn't working somehow. perhaps there's a library sa firebase to get the file name only.

2023-07-11 08:30 UTC, ezerssss commented on helpers/upload.ts
> +  return specificPart;
![image](https://github.com/ezerssss/unihub/assets/72904036/9187b6b9-c51f-46c0-818e-7209a7db4881)

asked manong chatGPT and we kinda have the same implementation

BUT anyways

does this work na? i was also thinking maybe sa reference sa function mismo ang wrong?

2023-07-11 08:32 UTC, ezerssss commented on services/product.ts
> +      const imagePath = `products/${imageID}`;
this is what i mean na wrong reference, maybe we should a `.jpeg` sa imageID?

we can add it here like 
```
const imagePath = `products/${imageID}.jpeg`;
````

or I think even better is sa `getImageID` returned na there ang `.jpeg`

2023-07-11 08:33 UTC, ezerssss commented on helpers/upload.ts
> +  return specificPart;
maybe add something like
```
return `${specificPart}.jpeg`
```

2023-07-11 10:44 UTC, HansGabriel commented on helpers/upload.ts
> +  return specificPart;
yeah forgot the jpeg haha

2023-07-11 10:46 UTC, HansGabriel commented on screens/Sell/EditSell.tsx
Um I initially planned to reuse the component but I feel like the logic would be too coupled. Usually I try to follow the rule of thirds where if it's repeated the third time, then we'll refactor it. What do you think?

https://en.wikipedia.org/wiki/Rule_of_thirds

2023-07-11 11:41 UTC, ezerssss commented on screens/Sell/EditSell.tsx
ooohh okok, TIL haha thanks!

yeah we can keep it this way

2023-07-12 10:59 UTC, ezerssss approved these changes

2023-07-12 12:19 UTC, merged