[UI] [Louie] Transaction Order UI
ezerssss/unihub pull request #105
Opened 2023-07-12 09:38 UTC by cezro

Clickup Subtask: https://app.clickup.com/t/865cput4y

- Order UI buttons and listing
- Pending and Order Request contrast not implemented

https://github.com/ezerssss/unihub/assets/90561528/494322c8-8309-41b9-a735-aa7af13dfd76

2023-07-12 11:36 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +          <Text className="mb-5 text-[#3838FC]">
export color to a constant

2023-07-12 11:38 UTC, ezerssss requested changes
Can you

- make the rounded buttons smaller, and the font size smaller (screen seems to be too tight)
- have a fixed 1/2 height for both your orders and your listings
- if no items sa that status maybe put an indicator or like text na no items or smth (refer: https://reactnative.dev/docs/flatlist#listemptycomponent)

2023-07-12 13:17 UTC, cezro commented
> * if no items sa that status maybe put an indicator or like text na no items or smth (refer: https://reactnative.dev/docs/flatlist#listemptycomponent)

i think theres something already like that, however doesn't show up tho

might be an issue with the `.length` method something like if it exists, tried replacing it with `.length !== 0` but still doesn't work. maybe missed something here

```ts
  const renderNoOrders = !isLoading && !orders.length && (
    <Text className="mx-3 text-sm text-gray-400">
      You do not have any orders.
    </Text>
  );
  const renderNoListings = !isLoading && !listings.length && (
    <Text className="mx-3 h-14 text-sm text-gray-400">
      Your products have no orders.
    </Text>
  );
  ```

2023-07-13 10:43 UTC, ezerssss commented on screens/Transactions/RoundedButton.tsx
> +      className={`max- mx-1 flex min-w-[85px] flex-row items-center justify-center rounded-full border border-primary-300 align-middle ${
`max-` remove

2023-07-13 10:43 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +    const renderChatListing = activeListingStatus !== StatusEnum.PENDING &&
dont remove the `StatusEnum.CANCEL` na logic

2023-07-13 10:43 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +      activeListingStatus !== StatusEnum.DENY && (
also add for `!== StatusEnum.CANCEL`

2023-07-13 10:43 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +                })
export to a constant

2023-07-13 10:43 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +    );
you can just store the data as a product, so the state can just be a `Product` state

2023-07-13 10:43 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +    const renderChatListing = activeListingStatus !== StatusEnum.PENDING &&
```
const isNotCancelledOrDenied = activeListingStatus !== StatusEnum.CANCEL && activeListingStatus !== StatusEnum.DENY;

const renderChatListing = activeListingStatus !== StatusEnum.PENDING && isNotCancelledOrDenied && user?.displayName === seller
```

2023-07-13 11:20 UTC, ezerssss approved these changes

2023-07-13 11:21 UTC, merged