[Adjustment][Sam] Chat Multiline Input
ezerssss/unihub pull request #128
Opened 2023-07-18 09:58 UTC by franzsamilo

**Clickup Task:**
https://app.clickup.com/t/865cqzt68

**Description:**
Added Chat text multiline input

**Images/Videos:
![361686307_959223821953657_6494236157514661605_n](https://github.com/ezerssss/unihub/assets/124412484/f231ea64-a356-43a5-88be-972aa0478ef4)
**

2023-07-18 10:10 UTC, ezerssss approved these changes

2023-07-19 16:51 UTC, jedmamosto requested changes
NICEEEE!!! it works but id like to request changes hehe

**Add more lines:**

it currently supports upto 3 lines of multi-line 

but 

can we have it support upto 6 lines? Messenger does this 

para this way we can give them a sense of familiarity with the chat - making the overall UX experience better

NONETHELESS

good job! thanks :))

2023-07-24 16:31 UTC, caspted approved these changes
Great job on making it support I think more than 10 plus lines

2023-07-24 16:38 UTC, jedmamosto approved these changes
GOODS!

2023-07-24 16:57 UTC, merged