[WIP] Transactions Enhancement
ezerssss/unihub pull request #133
Opened 2023-07-19 17:53 UTC by HansGabriel

**Clickup Task:**

**Description:**

**Images/Videos:**

2023-07-21 10:59 UTC, HansGabriel commented on services/notification.ts
> +    // alert('Must use physical device for Push Notifications.');
disabling for now since prompts can be annoying!

2023-07-24 04:39 UTC, ezerssss requested changes

2023-07-24 04:39 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +  const filteredListings = getProductsFromTransactions(
shouldn't be `getTransactionsFromProduct?`

2023-07-24 04:39 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +function getProductsFromTransactions(
`getTransactionsFromProduct` may be a better function name?

2023-07-24 04:39 UTC, ezerssss commented on types/product.ts
> +}
this seems to create a circular dependency? maybe transfer this nalang to the transactions file, since the transactions file has the product imported already

2023-07-24 04:39 UTC, ezerssss commented on screens/Transactions/Transactions.tsx
> +    );
can we export to its own file? and maybe even for the `handleRender` above too? kinda cluttered na ang main file, its so that we can also apply optimization techniques later on like `useMemo` for these components

2023-07-26 04:11 UTC, jedmamosto commented
@HansGabriel changes requested by @ezerssss

2023-07-27 10:12 UTC, HansGabriel commented on types/product.ts
> +}
I guess for this one it's not necessarily a circular dependency but product gets repeated twice.

2023-07-27 11:02 UTC, ezerssss commented on types/product.ts
> +}
pero diba the transactions.ts na file imports the product.ts na file, tapos here the products.ts na file imports the transactions.ts na file din creating a circular dependency

2023-07-27 11:13 UTC, ezerssss approved these changes

2023-07-27 14:05 UTC, jedmamosto commented
nong can you let us know next time if may new dependencies ka gn install? HAHAHAH para we can run `npm install`

2023-07-27 14:15 UTC, HansGabriel commented
> nong can you let us know next time if may new dependencies ka gn install? HAHAHAH para we can run `npm install`

Um if may changes sa `package.json` regarding dependencies then you have to install

2023-07-27 14:15 UTC, caspted requested changes
![357178478_1712046552589481_5202440592341158261_n](https://github.com/ezerssss/unihub/assets/124358735/84f3bdfe-ff9a-4d38-b6f0-e8d9673b83f0)

This icon seems to lift up from position when pressed

2023-07-27 14:19 UTC, jedmamosto commented
sheesh nong grabe HAHAHA requesting UI changes: 

**(1) Too close to the status bars...**
![image](https://github.com/ezerssss/unihub/assets/124409966/cbc737a9-6e5d-4fc3-a170-354b6046e4e2)

**(2) Should be rounded** 

_What it is:_
![image](https://github.com/ezerssss/unihub/assets/124409966/80dc3bc7-f87e-4ddb-959e-d93e250c5676)

_Should be:_
![image](https://github.com/ezerssss/unihub/assets/124409966/cefe4fa9-2627-4db3-afab-03530f3addc8)

**(3) Fix overlap**
![image](https://github.com/ezerssss/unihub/assets/124409966/0d2d2f4f-d256-4d84-b373-8e041dd67e17)

**(4) When you click on the product card it should redirect:**

![image](https://github.com/ezerssss/unihub/assets/124409966/9c835f71-cd2b-4a15-adab-30ff2d37b15b)

2023-07-27 14:23 UTC, jedmamosto commented
> ![357178478_1712046552589481_5202440592341158261_n](https://user-images.githubusercontent.com/124358735/256564955-84f3bdfe-ff9a-4d38-b6f0-e8d9673b83f0.jpg)
> 
> This icon seems to lift up from position when pressed

same issue

2023-07-27 15:13 UTC, jedmamosto commented
Red notifications should appear:

As product status updates, a red notification mark should appear.

As well as whenever a new update appears on either 'Your Order' or 'Your Listings', a red notification mark should appear.
![image](https://github.com/ezerssss/unihub/assets/124409966/6806e0ed-2141-4795-82a2-172d892f2432)

In order requests, the notebook icon should have a red notification for every new update.
![image](https://github.com/ezerssss/unihub/assets/124409966/60ba877c-9adc-4779-81ec-f29657c7479f)

Inside the notebook icon, every chat update should have a red notification mark too.

2023-08-01 13:04 UTC, merged