[Feature][Ezra] user page
ezerssss/unihub pull request #137
Opened 2023-07-21 05:08 UTC by ezerssss

**Clickup Task:**
https://app.clickup.com/t/865cr7ze0

**Description:**
User Page

**Images/Videos:**
![image](https://github.com/ezerssss/unihub/assets/72904036/7cdb6818-dea9-45c4-8407-56b3c00940a0)

2023-07-21 06:02 UTC, franzsamilo approved these changes

2023-07-21 07:36 UTC, caspted approved these changes
Looks good in android. keep the good work

2023-07-24 16:44 UTC, jedmamosto requested changes
Looks good ez! One last change...

Notification slider should have a 12px margin bottom between the line underneath it.

![image](https://github.com/ezerssss/unihub/assets/124409966/0471cbb8-babe-47b3-bdd3-7446622fba9f)

2023-07-24 16:59 UTC, jedmamosto approved these changes
goods!

2023-07-24 16:59 UTC, merged