[Adjustment][Sam] Footer UI & Navigation
ezerssss/unihub pull request #139
Opened 2023-07-21 10:46 UTC by franzsamilo

**Clickup Task:**
https://app.clickup.com/t/865cqywum
https://app.clickup.com/t/865cqyx6f

**Description:**
- Fixed Footer nav's alignment
- Fixed Navigations

- Nav Icon changes according to active screen (not yet tested since user screen is not yet merged)

**Images/Videos:**

https://github.com/ezerssss/unihub/assets/124412484/3caee6ec-6986-4cd1-973b-8200e1899b94

2023-07-21 10:54 UTC, HansGabriel approved these changes

2023-07-21 10:57 UTC, ezerssss requested changes

2023-07-21 10:57 UTC, ezerssss commented on components/Footer/Footer.tsx
> +  const [currentScreen, setCurrentScreen] = useState(Routes.HOME);
no need for `useState` i think kay u can use `useRoute` and it should give the current screen

![image](https://github.com/ezerssss/unihub/assets/72904036/58581391-c6bb-4201-9172-0d699c0f2eb4)

you can follow how i implemented it sa `useAuthHandler` na file

`route.name`

2023-07-21 11:07 UTC, ezerssss approved these changes

2023-07-24 16:09 UTC, jedmamosto requested changes
`Sell` doesn't seem centered? It looks off and feels off. 

Add more space between the indicator bar and the Footer components - they look tight.

![image](https://github.com/ezerssss/unihub/assets/124409966/1fbc1513-35f9-4c18-81f6-dfc1b52cd7b4)

2023-07-24 16:11 UTC, jedmamosto commented
Also I think before we can merge this, we need to have the User screen merged into main nadin?

2023-07-25 10:38 UTC, jedmamosto requested changes
Navigation works but... Home icon should change too

![image](https://github.com/ezerssss/unihub/assets/124409966/cee42604-413a-45d4-90e8-37346846e63e)

Should be: 

![image](https://github.com/ezerssss/unihub/assets/124409966/ddb1db1e-6c1c-493e-ba59-2d739fa05425)


Also sell doesn't seem to look centered still... its a bit off to the left and margin to the right of `Me` seems to be more compared to `Shop`

**What it looks like:** 
![image](https://github.com/ezerssss/unihub/assets/124409966/1a60041a-6fd8-4ccc-8b01-217014c146f3)


Also add space between the navigation icons like: (not exactly 14.43 but like close to that so maybe 14px or 16px)

![image](https://github.com/ezerssss/unihub/assets/124409966/05595064-237d-44da-9829-89927f9d006f)

2023-07-25 14:48 UTC, caspted commented
![20230725_224353](https://github.com/ezerssss/unihub/assets/124358735/cb6d30e7-617a-41e2-a35f-815b3c99e227)

The circle part at bottom is my home screen button and that is in the center of the screen so that is where you will base to move the Sell towards the center

2023-07-26 03:42 UTC, jedmamosto commented
`Sell` is still not centered... as well as it leans more on the left...

Here are spacing guidelines:
![image](https://github.com/ezerssss/unihub/assets/124409966/55227ea1-e2d2-45d7-b88f-b78655fae63e)
![image](https://github.com/ezerssss/unihub/assets/124409966/bd536b79-2b66-4144-84d3-5d9f04e9f11e)
![image](https://github.com/ezerssss/unihub/assets/124409966/cb72eee9-2836-4cc8-93e2-f14672f653d0)
![image](https://github.com/ezerssss/unihub/assets/124409966/3a1cee65-ae88-4d4c-862b-692483d61d34)

**_Always keep `Sell` at the center_**

2023-07-28 11:57 UTC, jedmamosto approved these changes

2023-07-28 11:58 UTC, merged