[Enhancment][Hans] add rounded corners for header
ezerssss/unihub pull request #144
Opened 2023-07-25 06:38 UTC by HansGabriel

**Clickup Task:**
https://app.clickup.com/t/865cr4efg

**Description:**
Add rounded corners for header

**Images/Videos:**
Followed this design:
![image](https://github.com/ezerssss/unihub/assets/49836841/d57a357a-0d9f-4041-a2f8-d94e068cbb9c)

2023-07-25 10:52 UTC, ezerssss approved these changes

2023-07-26 04:29 UTC, jedmamosto commented
Oof, I think you have to fix the conflicts first nong

I'm having this error: 

![image](https://github.com/ezerssss/unihub/assets/124409966/2901a7b8-9977-42d9-9734-7f76548faaa6)

2023-07-26 04:43 UTC, HansGabriel commented
> Oof, I think you have to fix the conflicts first nong
> 
> I'm having this error:
> 
> ![image](https://user-images.githubusercontent.com/124409966/256116724-2901a7b8-9977-42d9-9734-7f76548faaa6.png)

Um you have to run `npm install` first since I added new dependencies

2023-07-26 07:26 UTC, jedmamosto requested changes
Good job nong! However, I'd like to request some changes:

(1) Fix awkward `Sell` container - maybe have the sell container stick to the bottom? @ezerssss what do u think?

![image](https://github.com/ezerssss/unihub/assets/124409966/3fd0bcc5-485b-4a2a-94e1-70c5dbfbc1d8)


(2) Horizontally align `Category Picker` (category picker ang ma adjust) with `Category` + Have the category picker match font size and color with that of 'Enter product name', 'Enter product price' 

![image](https://github.com/ezerssss/unihub/assets/124409966/c934c70c-3468-4e66-98d3-a9055ee2069c)


(3) Have `Category Picker` (category picker ma adjust) vertically align with `Set` of Meetup Time, maybe setting it to flex-end tapos margin right of 12px? + Also have the font size and color match with that of 'Enter product price' and the like.

![image](https://github.com/ezerssss/unihub/assets/124409966/6d07cd8f-ad91-42b2-a7be-5084c60da624)

2023-07-26 14:24 UTC, ezerssss approved these changes

2023-07-26 14:30 UTC, caspted requested changes
![Screenshot_20230726-222409_Gallery](https://github.com/ezerssss/unihub/assets/124358735/6dd8c028-793b-4dd5-bbda-7b3510518662)

I request change for this in android since there is suppose to be a shadow there

2023-07-26 14:45 UTC, jedmamosto requested changes
Last change nong then goods na man

2023-07-26 14:45 UTC, jedmamosto commented on screens/Sell/CategoryPicker.tsx
> +          fontSize: 12,
Put it back to fontSize: 14 nong

2023-07-26 14:45 UTC, jedmamosto commented on screens/Sell/Sell.tsx
> +                      className={`text-md px-5 py-1 font-light ${timeColor}`}
there's not `text-md` in tailwind ata? perhaps use `text-xs` para 14px

2023-07-26 15:07 UTC, jedmamosto commented
`text-sm` gali nong mb

2023-07-26 15:16 UTC, jedmamosto approved these changes
noice

2023-07-26 15:35 UTC, merged