[Feature] [Louie] UI changes and Specific Product Navigation animation
ezerssss/unihub pull request #145
Opened 2023-07-25 07:07 UTC by cezro

**Clickup Task:**
https://app.clickup.com/t/865cr46kg

**Description:**
Slight UI changes to specific product page and transition animation

**Images/Videos:**
https://github.com/ezerssss/unihub/assets/90561528/143be1dc-47c1-4fd8-879d-efb8256267e4

2023-07-25 07:13 UTC, ezerssss commented on App.tsx
> +                }}
no need for `animationTypeForReplace: 'push'`?

2023-07-25 07:18 UTC, ezerssss approved these changes

2023-07-25 07:21 UTC, cezro commented on App.tsx
> +                }}
hmm not actually sure what that does, what kind of issues could it do?

2023-07-25 07:26 UTC, ezerssss commented on App.tsx
> +                }}
well for mine it didnt work, w/o it, pero if it does work then dats alright

just have to let QA figure it out HAHA

2023-07-25 07:31 UTC, cezro commented on App.tsx
> +                }}
might be an android issue, ill just resolve it if ever lmao

2023-07-25 10:47 UTC, jedmamosto requested changes
Animation looks good! BG color implementation is there but you forgot to implement changes for the margins: 

**WHAT IT LOOKS LIKE:** 

![image](https://github.com/ezerssss/unihub/assets/124409966/c2313f5b-a7ec-4e4c-9984-eff9ba612ccf)


**SHOULD BE: (it aligns vertically with the image)** 

![image](https://github.com/ezerssss/unihub/assets/124409966/6cee0484-1c0a-41a3-9596-92d1bd14572f)

![image](https://github.com/ezerssss/unihub/assets/124409966/49b97040-0947-4957-acf4-00077cf89252)

2023-07-26 04:05 UTC, jedmamosto commented
Oof you have merge conflicts Lou maybe have that resolves first

As for the requested changes, all good! Good job

2023-07-27 13:58 UTC, jedmamosto approved these changes
looks good! approved

2023-07-27 14:51 UTC, caspted approved these changes
Good job on this task the animation looks good and the details are aligned in android

2023-07-27 15:05 UTC, merged