[Feature][Hans] add product listings
ezerssss/unihub pull request #26
Opened 2023-06-12 08:38 UTC by HansGabriel

2023-06-12 09:27 UTC, ezerssss requested changes

2023-06-12 09:27 UTC, ezerssss commented on screens/ProductListings/ProductListings.tsx
> +];
transfer to data folder

2023-06-12 09:27 UTC, ezerssss commented on screens/ProductListings/types.ts
> +}
transfer to enums folder

2023-06-12 09:27 UTC, ezerssss commented on screens/ProductListings/types.ts
> +}
i was thinking we just reuse the same type `Product` 
we can have a new type `ProductListing[]` but I think it should be

`export interface ProductListing extends Product {
     status: ListingStatus;
}`

2023-06-12 09:27 UTC, ezerssss commented on screens/ProductListings/types.ts
> +}
or we can even just add status to the original `Product` type, I prefer it to just have one type for the product but its ur call

2023-06-12 09:59 UTC, HansGabriel commented on screens/ProductListings/types.ts
> +}
Hmm problem is the Product type is kinda coupled? I guess if we have finalized the fireabase schema, we can discuss how to improve the types, for now we're still guessing the possible shape. Maybe we can refactor in the future?

2023-06-12 10:27 UTC, ezerssss commented on screens/ProductListings/types.ts
> +}
because I was thinking, when a user uploads a product, the same data object will be uploaded under his own user collection

I also don't see a problem with using the same type for the listing, since it technically is just a product, and the product should contain what's its status is

if we go with this approach, integration is straightforward

2023-06-13 03:29 UTC, ezerssss approved these changes
lgtm

2023-06-13 03:32 UTC, merged