[Feature] [Order Confirmation]
ezerssss/unihub pull request #27
Opened 2023-06-13 13:39 UTC by cezro

https://github.com/ezerssss/unihub/assets/90561528/86a5c88c-e00d-43b7-9c2d-4b3f8804383f

-still don't have a way to fetch data from the database and linking product to specific product page

-also progress bar doesnt have a field on the product in the database

2023-06-13 14:49 UTC, HansGabriel commented on components/progressbar/ProgressBar.tsx
> +// currently no progress field in database
no need na comments ah.

2023-06-14 02:40 UTC, ezerssss requested changes
code looks good overall!

2023-06-14 02:40 UTC, ezerssss commented on components/progressbar/ProgressBar.tsx
> +// currently no progress field in database
remove comments

2023-06-14 02:40 UTC, ezerssss commented on components/progressbar/ProgressBar.tsx
> +    if (progress === 1) {
have an enum for this, you can do
```
enum Progress {
    ORDER_CONFIRMATION = 1,
    MEETUP = 2,
    SUCCESS = 3
}
```

this is so that we don't need to remember that 1 is for this 2 is for this etc..

2023-06-14 02:40 UTC, ezerssss commented on components/progressbar/ProgressBar.tsx
> +  function checkProgress(bar: number, progress: number): string {
give a more descriptive name

smth like `generateStyle`

2023-06-14 06:51 UTC, ezerssss approved these changes

2023-06-14 12:03 UTC, merged