[UI] [Sam] Text Overflow Fix & Color Changes
ezerssss/unihub pull request #45
Opened 2023-06-23 14:41 UTC by franzsamilo

2023-06-23 15:17 UTC, HansGabriel submitted a review, later dismissed

2023-06-23 15:17 UTC, HansGabriel commented on components/carousel/ProductsCarousel.tsx
> +    let formattedTitle = product.title;
can you use `const` instead?

2023-06-23 15:35 UTC, franzsamilo commented on components/carousel/ProductsCarousel.tsx
> +    let formattedTitle = product.title;
Can't, formattedTitle needs to change value if true ang if else statement.

2023-06-23 15:40 UTC, franzsamilo commented on screens/SpecificProduct/SpecificProduct.tsx
> +    while (indexEnd > 0 && product.title[indexEnd] !== ' ') {
that's just a checker to see if the slice method is not cutting words in half, so if indexEnd is a space then it'll slice there but if not the slice moves back until finds a space. indexEnd is 16 kay that's the max length of character nga d mag overflow ang title to other elements.

2023-06-24 05:46 UTC, ezerssss requested changes

2023-06-24 05:46 UTC, ezerssss commented on components/carousel/ProductsCarousel.tsx
> +    }
this can be skipped by just using the `numberOfLines` na method sang `Text`

read more here: https://stackoverflow.com/questions/30594080/how-to-have-ellipsis-effect-on-text#:~:text=Use%20the%20numberOfLines%20parameter%20on%20a%20Text%20component%3A

Just set the max-width of the `Text` component

2023-06-24 05:46 UTC, ezerssss commented on screens/SpecificProduct/SpecificProduct.tsx
> +
i dont understand wats this for? seems like a complex solution to an easy problem.

cant u just use CSS? can u provide a screenshot on wats this code doing?

2023-06-24 05:58 UTC, franzsamilo commented on screens/SpecificProduct/SpecificProduct.tsx
> +
true mb, new commit can you review?

2023-06-24 06:05 UTC, kasutu commented on screens/SpecificProduct/SpecificProduct.tsx
>                  </Text>
yeah, he can text wrap sa css tho.

use a container with a text-wrapping style. that way you can limit the text length.

2023-06-24 07:19 UTC, ezerssss approved these changes
lgtm

2023-06-24 09:02 UTC, merged