[Integration][Jerome] send chat messages
ezerssss/unihub pull request #47
Opened 2023-06-24 08:27 UTC by kasutu

this enables the sending of messages in the transaction

+ add testing library for future use

2023-06-24 09:09 UTC, ezerssss requested changes

2023-06-24 09:09 UTC, ezerssss commented on helpers/sendMessage.ts
> +    // add a message
remove comments

2023-06-24 09:09 UTC, ezerssss commented on __tests__/helpers/sendMessage.test.ts
> +      createdAt: new Date(),
did u update the type of the `Message`? this type doesn't fit well with my design

refer to the diagram for the type of the message

2023-06-24 09:09 UTC, ezerssss commented on __tests__/helpers/sendMessage.test.ts
> +    console.log(transactionData);
eslint didnt pick this up as an error? i think I disabled `console.logs`

2023-06-24 09:09 UTC, ezerssss commented on screens/Chat/Chat.tsx
> +      await sendMessage(transaction, newMessage);
the `newMessage` object should follow the type I listed in the chart

it should contain the `from` param so that we know who sent the email so we can display the message properly if its sent by the user or the other

2023-06-24 09:09 UTC, ezerssss commented on screens/Chat/Chat.tsx
u did not integrate pa pulling from the db noh? it seems like no collection listener is installed pa

![image](https://github.com/ezerssss/unihub/assets/72904036/4cefff45-08a1-4478-b2da-d9113d306dfd)


this listener's job is to update lang the message in real time so this also removes the necessity to update the state manually in `line 46`

2023-06-24 09:09 UTC, ezerssss commented on screens/Chat/Chat.tsx
also the name of the other user, it seems like `TedTeddy` pa din yung other username all the time.

2023-06-24 09:09 UTC, ezerssss commented on screens/Chat/Chat.tsx
these buttons are not integrated din noh?
![image](https://github.com/ezerssss/unihub/assets/72904036/2c9db691-5dbc-45f7-81c1-9339e0e36c95)


maybe we can do this on another pr, lets have this pr focused siguro on the messaging integration

2023-06-26 10:49 UTC, HansGabriel commented on __tests__/helpers/sendMessage.test.ts
> +    const transaction = doc(db, DB.TRANSACTIONS, 'MQ36lOHMqJMDCh0ZFGYb');
Wouldn't this not work if the document was deleted?

2023-06-26 10:50 UTC, ezerssss commented on __tests__/helpers/sendMessage.test.ts
> +    const transaction = doc(db, DB.TRANSACTIONS, 'MQ36lOHMqJMDCh0ZFGYb');
yep, its not even testing the sending message functionality, I think I commented above na I ignore muna ang unit testing, should I delete nalang the file noh? wdyt

2023-06-26 10:51 UTC, ezerssss approved these changes

2023-06-26 10:51 UTC, ezerssss approved these changes
ill approve lang to remove the needs changes from my previous review, ill merge after another dev approves

2023-06-26 11:16 UTC, HansGabriel commented on __tests__/helpers/sendMessage.test.ts
> +    const transaction = doc(db, DB.TRANSACTIONS, 'MQ36lOHMqJMDCh0ZFGYb');
Yeah maybe we can ignore unit tests for now since functionalities might change still right?

2023-06-26 13:23 UTC, merged