[Feature] [Sam] Upload/Sell Product Input Validation / Error Messages
ezerssss/unihub pull request #48
Opened 2023-06-24 11:21 UTC by franzsamilo

2023-06-24 16:24 UTC, HansGabriel approved these changes

2023-06-25 11:34 UTC, ezerssss requested changes

2023-06-25 11:34 UTC, ezerssss commented on screens/Sell/Sell.tsx
> +      }
can you put this in a separate function? so that `handleSell` job is to just upload to db

maybe something like `handleInputValidation`

2023-06-25 11:34 UTC, ezerssss commented on screens/Sell/Sell.tsx
> +      showErrorPopup('Something went wrong with posting your product.');
maybe we can give the `error.message` as the string?

2023-06-25 14:29 UTC, franzsamilo commented
New commit pa review

2023-06-26 08:35 UTC, ezerssss approved these changes

2023-06-26 10:54 UTC, merged